### ISSUE TITLE
Unable to replicate buckets

### ISSUE THREAD

**Issue by Aashiqps** [clyso/chorus#81]
I have installed chorus using helm and also configured chorus cli with exposing grpcAPI using nodeport. after creating a replication rule it is not replicating. only changes done in values.yaml are in below sections. can anybody help to identify the issue.

```
commonConfig:
  features:
    tagging: true
    acl: true
  storage:
    createRouting: true # create routing rules to route proxy requests to main storage
    createReplication: false # create replication rules to replicate data from main to other storages
    storages:
      one:
        address: <source-address>
        provider: MinIO
        isMain: true
        isSecure: true
      two:
        address: <destination-address>
        provider: MinIO
        isSecure: true


secret: |-
  storage:
    storages:
      one:
        address: <source-address>
        provider: MinIO
        isMain: true
        isSecure: true
        credentials:
          user1:
            accessKeyID: xxxx
            secretAccessKey: xxxx
      two:
        address: <destination-address>
        provider: MinIO
        isMain: false
        isSecure: true
        credentials:
          user1:
            accessKeyID: xxxx
            secretAccessKey: xxxx
```
